name: CI
on:
  push:
    branches: [master]

jobs:
  test:
    name: Build, Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "17.x"

      - uses: pnpm/action-setup@v2.0.1
        name: Prepare
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build
        run: npm run-script build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build